return {
    [1] = {
        NodeId = 166,
        LocalPositionMeters = {-391.22, 751.13},
        Degree = 1,
        JunctionType = "DeadEnd",
        IsBridge = false,
        IsTunnel = false,
        Layer = "0",
        ConnectedRoadIds = {"28723279"},
        WidthsStuds = {5.0},
    },
    [2] = {
        NodeId = 167,
        LocalPositionMeters = {-367.89, 756.66},
        Degree = 1,
        JunctionType = "DeadEnd",
        IsBridge = false,
        IsTunnel = false,
        Layer = "0",
        ConnectedRoadIds = {"28723279"},
        WidthsStuds = {5.0},
    },
    [3] = {
        NodeId = 1229,
        LocalPositionMeters = {-258.72, 830.82},
        Degree = 1,
        JunctionType = "DeadEnd",
        IsBridge = false,
        IsTunnel = false,
        Layer = "0",
        ConnectedRoadIds = {"458274133"},
        WidthsStuds = {5.0},
    },
    [4] = {
        NodeId = 1708,
        LocalPositionMeters = {-370.03, 829.25},
        Degree = 1,
        JunctionType = "DeadEnd",
        IsBridge = false,
        IsTunnel = false,
        Layer = "0",
        ConnectedRoadIds = {"1102634651"},
        WidthsStuds = {5.0},
    },
}
