return {
    [1] = {
        Id = "462302434",
        Type = "LineString",
        Properties = {
            ["bicycle"] = "use_sidepath",
            ["cycleway:left"] = "separate",
            ["cycleway:right"] = "no",
            ["foot"] = "use_sidepath",
            ["highway"] = "primary",
            ["lanes"] = "2",
            ["lit"] = "yes",
            ["maxspeed:backward"] = "80",
            ["maxspeed:forward"] = "60",
            ["name"] = "Schleswig-Holstein-Straße",
            ["ref"] = "L 284",
            ["sidewalk:left"] = "separate",
            ["sidewalk:right"] = "no",
            ["surface"] = "asphalt",
            ["osm_id"] = 462302434,
            ["tile_500"] = "NO_E567500_N5955000_500",
            ["tile_250"] = "NO_E567500_N5955000_250",
            ["LaneCount"] = 2,
            ["DirectionMode"] = "two-way",
            ["OSMWidthMeters"] = 18.0,
            ["ScaledOSMWidthStuds"] = 64.285704,
            ["GameplayMinimumStuds"] = 28.0,
            ["FinalWidthStuds"] = 64.285704,
            ["crossing"] = "",
            ["stop"] = "",
            ["traffic_signals"] = "",
            ["sidewalk"] = "",
        },
        Geometry = {
            {1176.81, 4597.01}, {1171.68, 4619.60}
        }
    },
    [2] = {
        Id = "690921115",
        Type = "LineString",
        Properties = {
            ["bicycle"] = "use_sidepath",
            ["cycleway:left"] = "separate",
            ["cycleway:right"] = "no",
            ["foot"] = "use_sidepath",
            ["highway"] = "primary",
            ["lanes"] = "2",
            ["lit"] = "yes",
            ["maxspeed:backward"] = "80",
            ["maxspeed:forward"] = "60",
            ["name"] = "Schleswig-Holstein-Straße",
            ["ref"] = "L 284",
            ["sidewalk:left"] = "separate",
            ["sidewalk:right"] = "no",
            ["surface"] = "asphalt",
            ["osm_id"] = 690921115,
            ["tile_500"] = "NO_E567500_N5955000_500",
            ["tile_250"] = "NO_E567500_N5955000_250",
            ["LaneCount"] = 2,
            ["DirectionMode"] = "two-way",
            ["OSMWidthMeters"] = 18.0,
            ["ScaledOSMWidthStuds"] = 64.285704,
            ["GameplayMinimumStuds"] = 28.0,
            ["FinalWidthStuds"] = 64.285704,
            ["crossing"] = "",
            ["stop"] = "",
            ["traffic_signals"] = "",
            ["sidewalk"] = "",
        },
        Geometry = {
            {1183.50, 4557.63}, {1181.46, 4575.23}, {1176.81, 4597.01}
        }
    },
    [3] = {
        Id = "911544867",
        Type = "LineString",
        Properties = {
            ["bicycle"] = "use_sidepath",
            ["cycleway:left"] = "separate",
            ["cycleway:right"] = "no",
            ["foot"] = "use_sidepath",
            ["highway"] = "primary",
            ["lanes"] = "2",
            ["lit"] = "no",
            ["maxspeed:backward"] = "80",
            ["maxspeed:forward"] = "60",
            ["name"] = "Schleswig-Holstein-Straße",
            ["oneway"] = "no",
            ["ref"] = "L 284",
            ["sidewalk:left"] = "separate",
            ["sidewalk:right"] = "no",
            ["surface"] = "asphalt",
            ["osm_id"] = 911544867,
            ["tile_500"] = "NO_E567500_N5955000_500",
            ["tile_250"] = "NO_E567500_N5955000_250",
            ["LaneCount"] = 2,
            ["DirectionMode"] = "two-way",
            ["OSMWidthMeters"] = 18.0,
            ["ScaledOSMWidthStuds"] = 64.285704,
            ["GameplayMinimumStuds"] = 28.0,
            ["FinalWidthStuds"] = 64.285704,
            ["crossing"] = "",
            ["stop"] = "",
            ["traffic_signals"] = "",
            ["sidewalk"] = "",
        },
        Geometry = {
            {1195.43, 4401.00}, {1188.04, 4506.71}, {1184.84, 4542.88}, {1183.50, 4557.63}
        }
    },
}
