return {
    [1] = {
        Id = "3797279660",
        Type = "Point",
        Properties = {
            ["bus"] = "yes",
            ["name"] = "Garstedt, Marommer Straße (Ost)",
            ["network"] = "HVV",
            ["public_transport"] = "stop_position",
            ["osm_id"] = 3797279660,
            ["tile_500"] = "NO_E565500_N5949500_500",
            ["tile_250"] = "NO_E565500_N5949500_250",
            ["amenity"] = "",
            ["shop"] = "",
            ["railway"] = "",
        },
        Geometry = {
            {-671.72, -989.31}
        }
    },
    [2] = {
        Id = "736832506",
        Type = "LineString",
        Properties = {
            ["addr:city"] = "Norderstedt",
            ["addr:country"] = "DE",
            ["addr:housenumber"] = "101",
            ["addr:postcode"] = "22850",
            ["addr:street"] = "Ulzburger Straße",
            ["amenity"] = "fuel",
            ["brand"] = "OIL!",
            ["brand:wikidata"] = "Q2007561",
            ["brand:wikipedia"] = "de:OIL! Tankstellen",
            ["compressed_air"] = "yes",
            ["fuel:diesel"] = "yes",
            ["fuel:e10"] = "yes",
            ["fuel:lpg"] = "yes",
            ["fuel:octane_95"] = "yes",
            ["fuel:octane_98"] = "yes",
            ["landuse"] = "retail",
            ["name"] = "OIL!",
            ["opening_hours"] = "Mo-Fr 06:00-22:00; Sa-Su,PH 07:00-22:00",
            ["payment:american_express"] = "yes",
            ["payment:apple_pay"] = "yes",
            ["payment:cash"] = "yes",
            ["payment:coins"] = "yes",
            ["payment:contactless"] = "yes",
            ["payment:credit_cards"] = "yes",
            ["payment:debit_cards"] = "yes",
            ["payment:dkv"] = "yes",
            ["payment:girocard"] = "yes",
            ["payment:girogo"] = "yes",
            ["payment:google_pay"] = "yes",
            ["payment:logpay"] = "yes",
            ["payment:maestro"] = "yes",
            ["payment:mastercard"] = "yes",
            ["payment:notes"] = "yes",
            ["payment:novofleet"] = "yes",
            ["payment:roadrunner"] = "yes",
            ["payment:uta"] = "yes",
            ["payment:v_pay"] = "yes",
            ["payment:visa"] = "yes",
            ["payment:visa_debit"] = "yes",
            ["phone"] = "+49 40 5253231",
            ["website"] = "https://www.oil-tankstellen.de/tankstellen-tankstationen/tankstellenfinder-kraftstoffpreise-benzinpreise/tankstelle/ulzburger-strasse-101-22850-norderstedt/",
            ["osm_id"] = 736832506,
            ["tile_500"] = "NO_E565500_N5949500_500",
            ["tile_250"] = "NO_E565500_N5949500_250",
            ["shop"] = "",
            ["public_transport"] = "",
            ["railway"] = "",
        },
        Geometry = {
            {-601.52, -983.37}, {-615.21, -986.17}, {-601.64, -1028.54}, {-576.13, -1020.39}, {-584.03, -998.00}, {-584.34, -997.10}, {-589.85, -989.58}, {-595.40, -986.03}, {-601.52, -983.37}
        }
    },
    [3] = {
        Id = "8328616468",
        Type = "Point",
        Properties = {
            ["bus"] = "yes",
            ["name"] = "Garstedt, Marommer Straße (Ost)",
            ["public_transport"] = "stop_position",
            ["osm_id"] = 8328616468,
            ["tile_500"] = "NO_E565500_N5949500_500",
            ["tile_250"] = "NO_E565500_N5949500_250",
            ["amenity"] = "",
            ["shop"] = "",
            ["railway"] = "",
        },
        Geometry = {
            {-604.91, -916.86}
        }
    },
}
