return {
    [1] = {
        Id = "601012677",
        Type = "Point",
        Properties = {
            ["addr:city"] = "Norderstedt",
            ["addr:housenumber"] = "328",
            ["addr:postcode"] = "22846",
            ["addr:street"] = "Ulzburger Straße",
            ["amenity"] = "fast_food",
            ["branch"] = "Norderstedt",
            ["brand"] = "Smiley's",
            ["brand:wikidata"] = "Q60998945",
            ["cuisine"] = "pizza",
            ["delivery"] = "yes",
            ["diet:vegetarian"] = "yes",
            ["drive_through"] = "no",
            ["email"] = "info@smileys.de",
            ["name"] = "Smiley's",
            ["opening_hours"] = "Mo-Su 11:00-00:00",
            ["operator"] = "Smiley's Franchise GmbH",
            ["payment:cash"] = "yes",
            ["payment:ec_cards"] = "yes",
            ["phone"] = "+49 40 5261199",
            ["ref:vatin"] = "DE813331054",
            ["smoking"] = "no",
            ["takeaway"] = "yes",
            ["website"] = "https://www.smileys.de/bestellen/Norderstedt",
            ["wheelchair"] = "yes",
            ["osm_id"] = 601012677,
            ["tile_500"] = "NO_E566000_N5952000_500",
            ["tile_250"] = "NO_E566000_N5952250_250",
            ["shop"] = "",
            ["public_transport"] = "",
            ["railway"] = "",
        },
        Geometry = {
            {-98.83, 814.76}
        }
    },
}
