return {
    [1] = {
        Id = "2183115064",
        Type = "Point",
        Properties = {
            ["addr:city"] = "Norderstedt",
            ["addr:housenumber"] = "324",
            ["addr:postcode"] = "22846",
            ["addr:street"] = "Ulzburger Straße",
            ["amenity"] = "cafe",
            ["check_date"] = "2022-11-29",
            ["cuisine"] = "cake;coffee;breakfast;pastry",
            ["name"] = "Bäckerei Nitt - Café an der Ulzburger Straße 324",
            ["opening_hours"] = "Mo-Fr 06:00-18:00; Sa 06:00-12:00; Su 07:00-12:00",
            ["operator"] = "Bäckerei-Konditorei Nitt",
            ["outdoor_seating"] = "yes",
            ["phone"] = "+49 40 81972950",
            ["shop"] = "bakery",
            ["toilets:wheelchair"] = "no",
            ["website"] = "https://www.baeckerei-nitt.de/filialen/norderstedt/",
            ["wheelchair"] = "yes",
            ["osm_id"] = 2183115064,
            ["tile_500"] = "NO_E566000_N5952000_500",
            ["tile_250"] = "NO_E566000_N5952000_250",
            ["public_transport"] = "",
            ["railway"] = "",
        },
        Geometry = {
            {-100.57, 784.59}
        }
    },
    [2] = {
        Id = "455482288",
        Type = "Point",
        Properties = {
            ["amenity"] = "restaurant",
            ["indoor_seating"] = "yes",
            ["name"] = "Flame",
            ["outdoor_seating"] = "yes",
            ["wheelchair"] = "no",
            ["osm_id"] = 455482288,
            ["tile_500"] = "NO_E566000_N5952000_500",
            ["tile_250"] = "NO_E566000_N5952000_250",
            ["shop"] = "",
            ["public_transport"] = "",
            ["railway"] = "",
        },
        Geometry = {
            {-75.92, 619.29}
        }
    },
    [3] = {
        Id = "732830904",
        Type = "Point",
        Properties = {
            ["addr:city"] = "Norderstedt",
            ["addr:housenumber"] = "308-310",
            ["addr:postcode"] = "22846",
            ["addr:street"] = "Ulzburger Straße",
            ["branch"] = "Ulzburger Meile",
            ["brand"] = "PENNY",
            ["brand:wikidata"] = "Q284688",
            ["brand:wikipedia"] = "en:Penny (supermarket)",
            ["currency:EUR"] = "yes",
            ["name"] = "PENNY",
            ["opening_hours"] = "Mo-Sa 07:00-22:00",
            ["organic"] = "yes",
            ["payment:cash"] = "yes",
            ["payment:coins"] = "yes",
            ["payment:contactless"] = "yes",
            ["payment:credit_cards"] = "yes",
            ["payment:debit_cards"] = "yes",
            ["payment:girocard"] = "yes",
            ["payment:mastercard"] = "yes",
            ["payment:visa"] = "yes",
            ["payment:visa_debit"] = "yes",
            ["shop"] = "supermarket",
            ["wheelchair"] = "yes",
            ["osm_id"] = 732830904,
            ["tile_500"] = "NO_E566000_N5952000_500",
            ["tile_250"] = "NO_E566000_N5952000_250",
            ["amenity"] = "",
            ["public_transport"] = "",
            ["railway"] = "",
        },
        Geometry = {
            {-90.92, 644.81}
        }
    },
}
